#hamada
version: 2
jobs:
   build:
     docker:
       - image: mareimorsy/light-base
     steps:
       - checkout
       - run:
           name: "Docker authentication"
           command: 
              docker login -u $DOCKER_USER -p $DOCKER_PASS

       - run: |
           name: "Build & Push Docker image"
           command: |
              docker build -t nadamohamed2222/newimg:v1 .
              docker push nadamohamed2222/newimg:v1
           
